baseURL = 'https://crosser-of-river.github.io/'
languageCode = 'zh-cn'
defaultContentLanguage = "zh-cn"
title = 'investigatorzcyçš„è‡ªç•™åœ°'
theme = "PaperMod"
defaultTheme = "auto"
disableThemeToggle = true

[params]
  description = "è¿™æ˜¯æˆ‘çš„ä¸ªäººåšå®¢"
   [params.homeInfoParams]
    Title = "Hi there ğŸ‘‹"
    Content = "Can be Info, links, about..."