name: Deploy Hugo to GitHub Pages

on:
  push: # 当你向 main 分支推送代码时触发
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive # 重要！用于拉取你的主题子模块
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify # 构建网站，并压缩输出文件

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }} # 这里需要一个令牌
          external_repository: Crosser-of-River/Crosser-of-River.github.io # 你的 Pages 仓库
          publish_dir: ./public # Hugo 生成的静态文件目录
          publish_branch: main # 部署到 Pages 仓库的 main 分支
          cname: # 如果你有自定义域名，可以在这里填写，没有则留空 
